services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./static:/app/staticfiles
      - ./media:/app/coqueiral/produtos
    command: gunicorn --bind 0.0.0.0:8000 coqueiral.wsgi:application

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_coqueiral
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: